pr:
  - master

jobs:
- job: xcodebuild

  pool:
    vmImage: 'macos-10.15'
  variables:
    CI: true

  strategy:
    matrix:
      build_command: [
        'macos_build FluentUITester-macOS Debug build',
        'macos_build FluentUITester-macOS Release build',
        'ios_simulator_build FluentUITester-iOS Debug build',
        'ios_simulator_build FluentUITester-iOS Release build',
      ]

  steps:
    - checkout: self
      persistCredentials: true

    # Clean Derived Data
    - script: |
        rm -rf $(Build.Repository.LocalPath)/DerivedData
      displayName: 'Clean DerivedData'

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        sudo gem install cocoapods
      displayName: 'Install Cocoapods Environment'

    - script: |
        yarn
      displayName: 'yarn'

    - script: |
        yarn checkchange
      displayName: 'check change'

    - script: |
        yarn build
      displayName: 'yarn build'

    - script: |
        yarn check-for-changed-files
      displayName: 'Verify API and Ensure Changed Files'

    - script: |
        yarn bundle
      displayName: 'yarn bundle'

    - name: scripts/xcodebuild_wrapper.sh ${{ matrix.build_command }}
      run: scripts/xcodebuild_wrapper.sh ${{ matrix.build_command }}
